<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    public function run(): void
    {
        $countries = [
            ['num_code' => 4,   'alpha_2' => 'AF', 'alpha_3' => 'AFG', 'country_name' => 'Afghanistan',                          'dialing_code' => '+93'],
            ['num_code' => 8,   'alpha_2' => 'AL', 'alpha_3' => 'ALB', 'country_name' => 'Albania',                               'dialing_code' => '+355'],
            ['num_code' => 12,  'alpha_2' => 'DZ', 'alpha_3' => 'DZA', 'country_name' => 'Algeria',                               'dialing_code' => '+213'],
            ['num_code' => 20,  'alpha_2' => 'AD', 'alpha_3' => 'AND', 'country_name' => 'Andorra',                               'dialing_code' => '+376'],
            ['num_code' => 24,  'alpha_2' => 'AO', 'alpha_3' => 'AGO', 'country_name' => 'Angola',                                'dialing_code' => '+244'],
            ['num_code' => 32,  'alpha_2' => 'AR', 'alpha_3' => 'ARG', 'country_name' => 'Argentina',                             'dialing_code' => '+54'],
            ['num_code' => 31,  'alpha_2' => 'AZ', 'alpha_3' => 'AZE', 'country_name' => 'Azerbaijan',                            'dialing_code' => '+994'],
            ['num_code' => 36,  'alpha_2' => 'AU', 'alpha_3' => 'AUS', 'country_name' => 'Australia',                             'dialing_code' => '+61'],
            ['num_code' => 40,  'alpha_2' => 'AT', 'alpha_3' => 'AUT', 'country_name' => 'Austria',                               'dialing_code' => '+43'],
            ['num_code' => 48,  'alpha_2' => 'BH', 'alpha_3' => 'BHR', 'country_name' => 'Bahrain',                               'dialing_code' => '+973'],
            ['num_code' => 50,  'alpha_2' => 'BD', 'alpha_3' => 'BGD', 'country_name' => 'Bangladesh',                            'dialing_code' => '+880'],
            ['num_code' => 56,  'alpha_2' => 'BE', 'alpha_3' => 'BEL', 'country_name' => 'Belgium',                               'dialing_code' => '+32'],
            ['num_code' => 64,  'alpha_2' => 'BT', 'alpha_3' => 'BTN', 'country_name' => 'Bhutan',                                'dialing_code' => '+975'],
            ['num_code' => 68,  'alpha_2' => 'BO', 'alpha_3' => 'BOL', 'country_name' => 'Bolivia',                               'dialing_code' => '+591'],
            ['num_code' => 70,  'alpha_2' => 'BA', 'alpha_3' => 'BIH', 'country_name' => 'Bosnia and Herzegovina',                'dialing_code' => '+387'],
            ['num_code' => 72,  'alpha_2' => 'BW', 'alpha_3' => 'BWA', 'country_name' => 'Botswana',                              'dialing_code' => '+267'],
            ['num_code' => 76,  'alpha_2' => 'BR', 'alpha_3' => 'BRA', 'country_name' => 'Brazil',                                'dialing_code' => '+55'],
            ['num_code' => 96,  'alpha_2' => 'BN', 'alpha_3' => 'BRN', 'country_name' => 'Brunei',                                'dialing_code' => '+673'],
            ['num_code' => 100, 'alpha_2' => 'BG', 'alpha_3' => 'BGR', 'country_name' => 'Bulgaria',                              'dialing_code' => '+359'],
            ['num_code' => 104, 'alpha_2' => 'MM', 'alpha_3' => 'MMR', 'country_name' => 'Myanmar',                               'dialing_code' => '+95'],
            ['num_code' => 108, 'alpha_2' => 'BI', 'alpha_3' => 'BDI', 'country_name' => 'Burundi',                               'dialing_code' => '+257'],
            ['num_code' => 116, 'alpha_2' => 'KH', 'alpha_3' => 'KHM', 'country_name' => 'Cambodia',                              'dialing_code' => '+855'],
            ['num_code' => 120, 'alpha_2' => 'CM', 'alpha_3' => 'CMR', 'country_name' => 'Cameroon',                              'dialing_code' => '+237'],
            ['num_code' => 124, 'alpha_2' => 'CA', 'alpha_3' => 'CAN', 'country_name' => 'Canada',                                'dialing_code' => '+1'],
            ['num_code' => 140, 'alpha_2' => 'CF', 'alpha_3' => 'CAF', 'country_name' => 'Central African Republic',              'dialing_code' => '+236'],
            ['num_code' => 144, 'alpha_2' => 'LK', 'alpha_3' => 'LKA', 'country_name' => 'Sri Lanka',                             'dialing_code' => '+94'],
            ['num_code' => 152, 'alpha_2' => 'CL', 'alpha_3' => 'CHL', 'country_name' => 'Chile',                                 'dialing_code' => '+56'],
            ['num_code' => 156, 'alpha_2' => 'CN', 'alpha_3' => 'CHN', 'country_name' => 'China',                                 'dialing_code' => '+86'],
            ['num_code' => 170, 'alpha_2' => 'CO', 'alpha_3' => 'COL', 'country_name' => 'Colombia',                              'dialing_code' => '+57'],
            ['num_code' => 178, 'alpha_2' => 'CG', 'alpha_3' => 'COG', 'country_name' => 'Congo',                                 'dialing_code' => '+242'],
            ['num_code' => 180, 'alpha_2' => 'CD', 'alpha_3' => 'COD', 'country_name' => 'Democratic Republic of the Congo',      'dialing_code' => '+243'],
            ['num_code' => 188, 'alpha_2' => 'CR', 'alpha_3' => 'CRI', 'country_name' => 'Costa Rica',                            'dialing_code' => '+506'],
            ['num_code' => 191, 'alpha_2' => 'HR', 'alpha_3' => 'HRV', 'country_name' => 'Croatia',                               'dialing_code' => '+385'],
            ['num_code' => 192, 'alpha_2' => 'CU', 'alpha_3' => 'CUB', 'country_name' => 'Cuba',                                  'dialing_code' => '+53'],
            ['num_code' => 196, 'alpha_2' => 'CY', 'alpha_3' => 'CYP', 'country_name' => 'Cyprus',                                'dialing_code' => '+357'],
            ['num_code' => 203, 'alpha_2' => 'CZ', 'alpha_3' => 'CZE', 'country_name' => 'Czech Republic',                        'dialing_code' => '+420'],
            ['num_code' => 208, 'alpha_2' => 'DK', 'alpha_3' => 'DNK', 'country_name' => 'Denmark',                               'dialing_code' => '+45'],
            ['num_code' => 214, 'alpha_2' => 'DO', 'alpha_3' => 'DOM', 'country_name' => 'Dominican Republic',                    'dialing_code' => '+1-809'],
            ['num_code' => 218, 'alpha_2' => 'EC', 'alpha_3' => 'ECU', 'country_name' => 'Ecuador',                               'dialing_code' => '+593'],
            ['num_code' => 818, 'alpha_2' => 'EG', 'alpha_3' => 'EGY', 'country_name' => 'Egypt',                                 'dialing_code' => '+20'],
            ['num_code' => 222, 'alpha_2' => 'SV', 'alpha_3' => 'SLV', 'country_name' => 'El Salvador',                          'dialing_code' => '+503'],
            ['num_code' => 231, 'alpha_2' => 'ET', 'alpha_3' => 'ETH', 'country_name' => 'Ethiopia',                              'dialing_code' => '+251'],
            ['num_code' => 233, 'alpha_2' => 'EE', 'alpha_3' => 'EST', 'country_name' => 'Estonia',                               'dialing_code' => '+372'],
            ['num_code' => 246, 'alpha_2' => 'FI', 'alpha_3' => 'FIN', 'country_name' => 'Finland',                               'dialing_code' => '+358'],
            ['num_code' => 250, 'alpha_2' => 'FR', 'alpha_3' => 'FRA', 'country_name' => 'France',                                'dialing_code' => '+33'],
            ['num_code' => 266, 'alpha_2' => 'GA', 'alpha_3' => 'GAB', 'country_name' => 'Gabon',                                 'dialing_code' => '+241'],
            ['num_code' => 268, 'alpha_2' => 'GE', 'alpha_3' => 'GEO', 'country_name' => 'Georgia',                               'dialing_code' => '+995'],
            ['num_code' => 276, 'alpha_2' => 'DE', 'alpha_3' => 'DEU', 'country_name' => 'Germany',                               'dialing_code' => '+49'],
            ['num_code' => 288, 'alpha_2' => 'GH', 'alpha_3' => 'GHA', 'country_name' => 'Ghana',                                 'dialing_code' => '+233'],
            ['num_code' => 300, 'alpha_2' => 'GR', 'alpha_3' => 'GRC', 'country_name' => 'Greece',                                'dialing_code' => '+30'],
            ['num_code' => 320, 'alpha_2' => 'GT', 'alpha_3' => 'GTM', 'country_name' => 'Guatemala',                             'dialing_code' => '+502'],
            ['num_code' => 324, 'alpha_2' => 'GN', 'alpha_3' => 'GIN', 'country_name' => 'Guinea',                                'dialing_code' => '+224'],
            ['num_code' => 332, 'alpha_2' => 'HT', 'alpha_3' => 'HTI', 'country_name' => 'Haiti',                                 'dialing_code' => '+509'],
            ['num_code' => 340, 'alpha_2' => 'HN', 'alpha_3' => 'HND', 'country_name' => 'Honduras',                              'dialing_code' => '+504'],
            ['num_code' => 348, 'alpha_2' => 'HU', 'alpha_3' => 'HUN', 'country_name' => 'Hungary',                               'dialing_code' => '+36'],
            ['num_code' => 356, 'alpha_2' => 'IN', 'alpha_3' => 'IND', 'country_name' => 'India',                                 'dialing_code' => '+91'],
            ['num_code' => 360, 'alpha_2' => 'ID', 'alpha_3' => 'IDN', 'country_name' => 'Indonesia',                             'dialing_code' => '+62'],
            ['num_code' => 364, 'alpha_2' => 'IR', 'alpha_3' => 'IRN', 'country_name' => 'Iran',                                  'dialing_code' => '+98'],
            ['num_code' => 368, 'alpha_2' => 'IQ', 'alpha_3' => 'IRQ', 'country_name' => 'Iraq',                                  'dialing_code' => '+964'],
            ['num_code' => 372, 'alpha_2' => 'IE', 'alpha_3' => 'IRL', 'country_name' => 'Ireland',                               'dialing_code' => '+353'],
            ['num_code' => 376, 'alpha_2' => 'IL', 'alpha_3' => 'ISR', 'country_name' => 'Israel',                                'dialing_code' => '+972'],
            ['num_code' => 380, 'alpha_2' => 'IT', 'alpha_3' => 'ITA', 'country_name' => 'Italy',                                 'dialing_code' => '+39'],
            ['num_code' => 388, 'alpha_2' => 'JM', 'alpha_3' => 'JAM', 'country_name' => 'Jamaica',                               'dialing_code' => '+1-876'],
            ['num_code' => 392, 'alpha_2' => 'JP', 'alpha_3' => 'JPN', 'country_name' => 'Japan',                                 'dialing_code' => '+81'],
            ['num_code' => 400, 'alpha_2' => 'JO', 'alpha_3' => 'JOR', 'country_name' => 'Jordan',                                'dialing_code' => '+962'],
            ['num_code' => 398, 'alpha_2' => 'KZ', 'alpha_3' => 'KAZ', 'country_name' => 'Kazakhstan',                            'dialing_code' => '+7'],
            ['num_code' => 404, 'alpha_2' => 'KE', 'alpha_3' => 'KEN', 'country_name' => 'Kenya',                                 'dialing_code' => '+254'],
            ['num_code' => 408, 'alpha_2' => 'KP', 'alpha_3' => 'PRK', 'country_name' => 'North Korea',                           'dialing_code' => '+850'],
            ['num_code' => 410, 'alpha_2' => 'KR', 'alpha_3' => 'KOR', 'country_name' => 'South Korea',                           'dialing_code' => '+82'],
            ['num_code' => 414, 'alpha_2' => 'KW', 'alpha_3' => 'KWT', 'country_name' => 'Kuwait',                                'dialing_code' => '+965'],
            ['num_code' => 417, 'alpha_2' => 'KG', 'alpha_3' => 'KGZ', 'country_name' => 'Kyrgyzstan',                            'dialing_code' => '+996'],
            ['num_code' => 418, 'alpha_2' => 'LA', 'alpha_3' => 'LAO', 'country_name' => 'Laos',                                  'dialing_code' => '+856'],
            ['num_code' => 422, 'alpha_2' => 'LB', 'alpha_3' => 'LBN', 'country_name' => 'Lebanon',                               'dialing_code' => '+961'],
            ['num_code' => 426, 'alpha_2' => 'LS', 'alpha_3' => 'LSO', 'country_name' => 'Lesotho',                               'dialing_code' => '+266'],
            ['num_code' => 430, 'alpha_2' => 'LR', 'alpha_3' => 'LBR', 'country_name' => 'Liberia',                               'dialing_code' => '+231'],
            ['num_code' => 434, 'alpha_2' => 'LY', 'alpha_3' => 'LBY', 'country_name' => 'Libya',                                 'dialing_code' => '+218'],
            ['num_code' => 438, 'alpha_2' => 'LI', 'alpha_3' => 'LIE', 'country_name' => 'Liechtenstein',                         'dialing_code' => '+423'],
            ['num_code' => 440, 'alpha_2' => 'LT', 'alpha_3' => 'LTU', 'country_name' => 'Lithuania',                             'dialing_code' => '+370'],
            ['num_code' => 442, 'alpha_2' => 'LU', 'alpha_3' => 'LUX', 'country_name' => 'Luxembourg',                            'dialing_code' => '+352'],
            ['num_code' => 450, 'alpha_2' => 'MG', 'alpha_3' => 'MDG', 'country_name' => 'Madagascar',                            'dialing_code' => '+261'],
            ['num_code' => 454, 'alpha_2' => 'MW', 'alpha_3' => 'MWI', 'country_name' => 'Malawi',                                'dialing_code' => '+265'],
            ['num_code' => 458, 'alpha_2' => 'MY', 'alpha_3' => 'MYS', 'country_name' => 'Malaysia',                              'dialing_code' => '+60'],
            ['num_code' => 462, 'alpha_2' => 'MV', 'alpha_3' => 'MDV', 'country_name' => 'Maldives',                              'dialing_code' => '+960'],
            ['num_code' => 466, 'alpha_2' => 'ML', 'alpha_3' => 'MLI', 'country_name' => 'Mali',                                  'dialing_code' => '+223'],
            ['num_code' => 470, 'alpha_2' => 'MT', 'alpha_3' => 'MLT', 'country_name' => 'Malta',                                 'dialing_code' => '+356'],
            ['num_code' => 478, 'alpha_2' => 'MR', 'alpha_3' => 'MRT', 'country_name' => 'Mauritania',                            'dialing_code' => '+222'],
            ['num_code' => 484, 'alpha_2' => 'MX', 'alpha_3' => 'MEX', 'country_name' => 'Mexico',                                'dialing_code' => '+52'],
            ['num_code' => 496, 'alpha_2' => 'MN', 'alpha_3' => 'MNG', 'country_name' => 'Mongolia',                              'dialing_code' => '+976'],
            ['num_code' => 498, 'alpha_2' => 'MD', 'alpha_3' => 'MDA', 'country_name' => 'Moldova',                               'dialing_code' => '+373'],
            ['num_code' => 504, 'alpha_2' => 'MA', 'alpha_3' => 'MAR', 'country_name' => 'Morocco',                               'dialing_code' => '+212'],
            ['num_code' => 508, 'alpha_2' => 'MZ', 'alpha_3' => 'MOZ', 'country_name' => 'Mozambique',                            'dialing_code' => '+258'],
            ['num_code' => 516, 'alpha_2' => 'NA', 'alpha_3' => 'NAM', 'country_name' => 'Namibia',                               'dialing_code' => '+264'],
            ['num_code' => 524, 'alpha_2' => 'NP', 'alpha_3' => 'NPL', 'country_name' => 'Nepal',                                 'dialing_code' => '+977'],
            ['num_code' => 528, 'alpha_2' => 'NL', 'alpha_3' => 'NLD', 'country_name' => 'Netherlands',                           'dialing_code' => '+31'],
            ['num_code' => 540, 'alpha_2' => 'NC', 'alpha_3' => 'NCL', 'country_name' => 'New Caledonia',                         'dialing_code' => '+687'],
            ['num_code' => 554, 'alpha_2' => 'NZ', 'alpha_3' => 'NZL', 'country_name' => 'New Zealand',                           'dialing_code' => '+64'],
            ['num_code' => 558, 'alpha_2' => 'NI', 'alpha_3' => 'NIC', 'country_name' => 'Nicaragua',                             'dialing_code' => '+505'],
            ['num_code' => 562, 'alpha_2' => 'NE', 'alpha_3' => 'NER', 'country_name' => 'Niger',                                 'dialing_code' => '+227'],
            ['num_code' => 566, 'alpha_2' => 'NG', 'alpha_3' => 'NGA', 'country_name' => 'Nigeria',                               'dialing_code' => '+234'],
            ['num_code' => 578, 'alpha_2' => 'NO', 'alpha_3' => 'NOR', 'country_name' => 'Norway',                                'dialing_code' => '+47'],
            ['num_code' => 512, 'alpha_2' => 'OM', 'alpha_3' => 'OMN', 'country_name' => 'Oman',                                  'dialing_code' => '+968'],
            ['num_code' => 586, 'alpha_2' => 'PK', 'alpha_3' => 'PAK', 'country_name' => 'Pakistan',                              'dialing_code' => '+92'],
            ['num_code' => 591, 'alpha_2' => 'PA', 'alpha_3' => 'PAN', 'country_name' => 'Panama',                                'dialing_code' => '+507'],
            ['num_code' => 598, 'alpha_2' => 'PG', 'alpha_3' => 'PNG', 'country_name' => 'Papua New Guinea',                      'dialing_code' => '+675'],
            ['num_code' => 600, 'alpha_2' => 'PY', 'alpha_3' => 'PRY', 'country_name' => 'Paraguay',                              'dialing_code' => '+595'],
            ['num_code' => 604, 'alpha_2' => 'PE', 'alpha_3' => 'PER', 'country_name' => 'Peru',                                  'dialing_code' => '+51'],
            ['num_code' => 608, 'alpha_2' => 'PH', 'alpha_3' => 'PHL', 'country_name' => 'Philippines',                           'dialing_code' => '+63'],
            ['num_code' => 616, 'alpha_2' => 'PL', 'alpha_3' => 'POL', 'country_name' => 'Poland',                                'dialing_code' => '+48'],
            ['num_code' => 620, 'alpha_2' => 'PT', 'alpha_3' => 'PRT', 'country_name' => 'Portugal',                              'dialing_code' => '+351'],
            ['num_code' => 630, 'alpha_2' => 'PR', 'alpha_3' => 'PRI', 'country_name' => 'Puerto Rico',                           'dialing_code' => '+1-787'],
            ['num_code' => 634, 'alpha_2' => 'QA', 'alpha_3' => 'QAT', 'country_name' => 'Qatar',                                 'dialing_code' => '+974'],
            ['num_code' => 642, 'alpha_2' => 'RO', 'alpha_3' => 'ROU', 'country_name' => 'Romania',                               'dialing_code' => '+40'],
            ['num_code' => 643, 'alpha_2' => 'RU', 'alpha_3' => 'RUS', 'country_name' => 'Russia',                                'dialing_code' => '+7'],
            ['num_code' => 646, 'alpha_2' => 'RW', 'alpha_3' => 'RWA', 'country_name' => 'Rwanda',                                'dialing_code' => '+250'],
            ['num_code' => 682, 'alpha_2' => 'SA', 'alpha_3' => 'SAU', 'country_name' => 'Saudi Arabia',                          'dialing_code' => '+966'],
            ['num_code' => 686, 'alpha_2' => 'SN', 'alpha_3' => 'SEN', 'country_name' => 'Senegal',                               'dialing_code' => '+221'],
            ['num_code' => 688, 'alpha_2' => 'RS', 'alpha_3' => 'SRB', 'country_name' => 'Serbia',                                'dialing_code' => '+381'],
            ['num_code' => 694, 'alpha_2' => 'SL', 'alpha_3' => 'SLE', 'country_name' => 'Sierra Leone',                          'dialing_code' => '+232'],
            ['num_code' => 703, 'alpha_2' => 'SK', 'alpha_3' => 'SVK', 'country_name' => 'Slovakia',                              'dialing_code' => '+421'],
            ['num_code' => 705, 'alpha_2' => 'SI', 'alpha_3' => 'SVN', 'country_name' => 'Slovenia',                              'dialing_code' => '+386'],
            ['num_code' => 706, 'alpha_2' => 'SO', 'alpha_3' => 'SOM', 'country_name' => 'Somalia',                               'dialing_code' => '+252'],
            ['num_code' => 710, 'alpha_2' => 'ZA', 'alpha_3' => 'ZAF', 'country_name' => 'South Africa',                          'dialing_code' => '+27'],
            ['num_code' => 724, 'alpha_2' => 'ES', 'alpha_3' => 'ESP', 'country_name' => 'Spain',                                 'dialing_code' => '+34'],
            ['num_code' => 729, 'alpha_2' => 'SD', 'alpha_3' => 'SDN', 'country_name' => 'Sudan',                                 'dialing_code' => '+249'],
            ['num_code' => 752, 'alpha_2' => 'SE', 'alpha_3' => 'SWE', 'country_name' => 'Sweden',                                'dialing_code' => '+46'],
            ['num_code' => 756, 'alpha_2' => 'CH', 'alpha_3' => 'CHE', 'country_name' => 'Switzerland',                           'dialing_code' => '+41'],
            ['num_code' => 760, 'alpha_2' => 'SY', 'alpha_3' => 'SYR', 'country_name' => 'Syria',                                 'dialing_code' => '+963'],
            ['num_code' => 762, 'alpha_2' => 'TJ', 'alpha_3' => 'TJK', 'country_name' => 'Tajikistan',                            'dialing_code' => '+992'],
            ['num_code' => 764, 'alpha_2' => 'TH', 'alpha_3' => 'THA', 'country_name' => 'Thailand',                              'dialing_code' => '+66'],
            ['num_code' => 768, 'alpha_2' => 'TG', 'alpha_3' => 'TGO', 'country_name' => 'Togo',                                  'dialing_code' => '+228'],
            ['num_code' => 780, 'alpha_2' => 'TT', 'alpha_3' => 'TTO', 'country_name' => 'Trinidad and Tobago',                   'dialing_code' => '+1-868'],
            ['num_code' => 788, 'alpha_2' => 'TN', 'alpha_3' => 'TUN', 'country_name' => 'Tunisia',                               'dialing_code' => '+216'],
            ['num_code' => 792, 'alpha_2' => 'TR', 'alpha_3' => 'TUR', 'country_name' => 'Turkey',                                'dialing_code' => '+90'],
            ['num_code' => 795, 'alpha_2' => 'TM', 'alpha_3' => 'TKM', 'country_name' => 'Turkmenistan',                          'dialing_code' => '+993'],
            ['num_code' => 800, 'alpha_2' => 'UG', 'alpha_3' => 'UGA', 'country_name' => 'Uganda',                                'dialing_code' => '+256'],
            ['num_code' => 804, 'alpha_2' => 'UA', 'alpha_3' => 'UKR', 'country_name' => 'Ukraine',                               'dialing_code' => '+380'],
            ['num_code' => 784, 'alpha_2' => 'AE', 'alpha_3' => 'ARE', 'country_name' => 'United Arab Emirates',                  'dialing_code' => '+971'],
            ['num_code' => 826, 'alpha_2' => 'GB', 'alpha_3' => 'GBR', 'country_name' => 'United Kingdom',                        'dialing_code' => '+44'],
            ['num_code' => 840, 'alpha_2' => 'US', 'alpha_3' => 'USA', 'country_name' => 'United States',                         'dialing_code' => '+1'],
            ['num_code' => 858, 'alpha_2' => 'UY', 'alpha_3' => 'URY', 'country_name' => 'Uruguay',                               'dialing_code' => '+598'],
            ['num_code' => 860, 'alpha_2' => 'UZ', 'alpha_3' => 'UZB', 'country_name' => 'Uzbekistan',                            'dialing_code' => '+998'],
            ['num_code' => 862, 'alpha_2' => 'VE', 'alpha_3' => 'VEN', 'country_name' => 'Venezuela',                             'dialing_code' => '+58'],
            ['num_code' => 704, 'alpha_2' => 'VN', 'alpha_3' => 'VNM', 'country_name' => 'Vietnam',                               'dialing_code' => '+84'],
            ['num_code' => 887, 'alpha_2' => 'YE', 'alpha_3' => 'YEM', 'country_name' => 'Yemen',                                 'dialing_code' => '+967'],
            ['num_code' => 894, 'alpha_2' => 'ZM', 'alpha_3' => 'ZMB', 'country_name' => 'Zambia',                                'dialing_code' => '+260'],
            ['num_code' => 716, 'alpha_2' => 'ZW', 'alpha_3' => 'ZWE', 'country_name' => 'Zimbabwe',                              'dialing_code' => '+263'],
            ['num_code' => 8, 'alpha_2' => 'AL', 'alpha_3' => 'ALB', 'country_name' => 'Albania',                               'dialing_code' => '+355'],
            ['num_code' => 51,  'alpha_2' => 'AM', 'alpha_3' => 'ARM', 'country_name' => 'Armenia',                               'dialing_code' => '+374'],
            ['num_code' => 112, 'alpha_2' => 'BY', 'alpha_3' => 'BLR', 'country_name' => 'Belarus',                               'dialing_code' => '+375'],
            ['num_code' => 414, 'alpha_2' => 'KW', 'alpha_3' => 'KWT', 'country_name' => 'Kuwait',                                'dialing_code' => '+965'],
            ['num_code' => 434, 'alpha_2' => 'LY', 'alpha_3' => 'LBY', 'country_name' => 'Libya',                                 'dialing_code' => '+218'],
            ['num_code' => 807, 'alpha_2' => 'MK', 'alpha_3' => 'MKD', 'country_name' => 'North Macedonia',                       'dialing_code' => '+389'],
            ['num_code' => 499, 'alpha_2' => 'ME', 'alpha_3' => 'MNE', 'country_name' => 'Montenegro',                            'dialing_code' => '+382'],
            ['num_code' => 643, 'alpha_2' => 'RU', 'alpha_3' => 'RUS', 'country_name' => 'Russian Federation',                    'dialing_code' => '+7'],
        ];

        $unique = [];
        foreach ($countries as $country) {
            $unique[$country['num_code']] = $country;
        }

        $chunks = array_chunk(array_values($unique), 50);

        foreach ($chunks as $chunk) {
            Country::upsert(
                $chunk,
                ['num_code'],
                ['alpha_2', 'alpha_3', 'country_name', 'dialing_code', 'status']
            );
        }
    }
}
