server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;

    resolver 127.0.0.11 valid=10s ipv6=off;

    limit_req zone=egov burst=20 nodelay;

    index index.php;
    set $root_path '/var/www/html/public';
    root $root_path;

    error_log  /var/log/nginx/error.log notice;
    error_page 404 /404.html;
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/www;
    }

    location = /nginx_status {
        stub_status;
        allow 127.0.0.1;
        allow ::1;
        deny all;
    }

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    error_page 404 /index.php;

    location ~ \.php$ {
        set $upstream app:9000;
        fastcgi_pass $upstream;
        fastcgi_index /index.php;
        include fastcgi_params;
        fastcgi_split_path_info       ^(.+\.php)(/.+)$;
        fastcgi_param PATH_INFO       $fastcgi_path_info;
        fastcgi_param PATH_TRANSLATED $document_root$fastcgi_path_info;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_read_timeout          3600;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }
}
